config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:new, :create, :show, :index, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
    resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
  # has_many :lists, through: :bookmarks
end

# dependent :destory unless: -> { comment.blank? }

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def show; end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment, photos: [])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :comment %>
<%= f.association :movie, collection: Movie.all.order(:title), prompt: "Choose a Movie" %>
<p class="btn-bookmark" > <%= f.button :submit %></p>
<% end %>

app/views/bookmarks/new.html.erb
<div class="new-list">
<h1>My New Bookmark</h1>
<%= render 'form', bookmark: @bookmark %>
<%= link_to 'Back', lists_path, class: 'btn btn-info'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iWatchThis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<p class="btn-create" > <%= f.button :submit %> </p>
<% end %>

app/views/lists/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1484469475235-12770b43d008?ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDMxfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  iWatchThis
</div>
<div class="new-list">
<h1>My lists</h1>
<table class="table thead-dark">
  <thead>
    <tr>
      <th scope="col"><%= "No" %></th>
      <th scope="col"> <%= "Name" %> </th>
      <th scope="col"> <%= "" %> </th>
      <th scope="col"> <%= "" %> </th>
    </tr>
  </thead>

  <tbody>
  <% @lists.each do |list| %>
    <tr>
      <th scope="row"><%= list.id %></th>
      <td><%= list.name %> </td>
      <td><%= link_to 'Show', list %></td>
      <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New List', new_list_path, class: 'btn btn-primary' %>
</div>

app/views/lists/new.html.erb
<div class="new-list">
<h1>My New List</h1>

<%= render 'form', list: @list %>
<div class="card-trip">
<%= link_to 'Back', lists_path, class: 'btn btn-info' %>
</div>

app/views/lists/show.html.erb
<div class="cards" >

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
  <%= @list.name %>
</div>
</div>



<% @list.bookmarks.each do |bookmark| %>
  <div class="card-product">
    <img src="<%= bookmark.movie.poster_url %>" alt="movie poster">
    <div class="card-product-infos">
      <h2><%= bookmark.movie.title %></h2>
      <p><%= bookmark.comment %></p>
    </div>
    <div class="del"><%= link_to "🗑", bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></div>
  </div>
<% end %>


<br>





<div>
<%= link_to 'Back', lists_path, class: 'btn btn-info' %>
<%= link_to 'Add Bookmark', new_list_bookmark_path(@list), class: 'btn btn-success' %>
</div>